# Generated by Django 4.0.6 on 2022-07-22 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TrySite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkey',
            name='id',
        ),
        migrations.AlterField(
            model_name='userkey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
