# Generated by Django 4.0.6 on 2022-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrySite', '0002_remove_userkey_id_alter_userkey_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpassword',
            name='login',
            field=models.CharField(max_length=255, unique=True, verbose_name='login'),
        ),
    ]
